# Generated by Django 6.1.1 on 2026-09-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('oauth_client', models.CharField(blank=True, default='', max_length=255)),
                ('tool', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('device_type', models.CharField(blank=True, default='laptop', max_length=64)),
                ('status', models.CharField(default='available', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_orders', to='organizations.organization')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_orders', to='retriever.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('closed', 'Closed')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='retriever.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
